name: Python CI Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 簡化：直接讀取 requirements.txt

    - name: Lint with flake8 (Check code style)
      run: |
        # 忽略 E402 錯誤（模組級導入不在頂部）
        flake8 . --count --show-source --statistics --ignore=E402

    - name: Test with pytest (Run unit tests)
      run: |
        # 使用 -v 選項獲得更詳細的輸出
        python -m pytest -v